# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf62ad7847af48f36ed5e0177a602c1cf66df0fd0c9595b32bb1ac6eea8913f1024ab79a784202575c874fb34ae926ba5e5ce7c528e33e601fc7ae8edd681565

test:
  secret_key_base: 2b30e758b257ef12055ed8df0fea2baf20b8de2bc315b17e1e5cccbfc278cf3109f11f415ea5545f265c0a1b87213f10bffcd9921651333a38752fd5149042e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
